[package]
name = "BBSP"
version = "0.1.0"
authors = ["Mengling-L <mengling@connect.hku.hk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bls12_381 = "0.8.0"
rand_chacha = "0.3.1"
ff = "0.13.0"